version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-kb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/matheus/mongodb:/data/db

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-kb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1-kb
    hostname: rabbitmq1
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: "bridge"
    volumes:
     - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest

volumes:
  postgres:
    driver: local
